### PR TITLE
plugins/neotest: init

### LINKED ISSUE #704: Add support for neotest
**Plugin**: neotest
**Plugin repository**: [URL to the repository of the plugin](https://github.com/nvim-neotest/neotest)
**Is the plugin on nixpkgs**: Yes

## Extra information

It is a common library used for setting up running tests in neovim. Would be great to see supported :).

### PR DESCRIPTION
**Pull request by GaetanLepage**
Add support for [neotest](https://github.com/nvim-neotest/neotest).

Fixes #704

### CODE REVIEW

**Comment by adalessa** [comment]
Hey, I started to draft something for neotest without realising you already have this in progress.  I put it as draft here #856 what is missing is the general configuration that you already have done. I included all the adapters that currently are in nixpkgs.
Once this is finished I can add them to this structure, or if not plans to finalize this for now I can copy the configuration section and push it for review. what do you think ?

**Comment by purepani** [comment]
Hey, just wanted to ask if this could be merged potentially.

**Comment by GaetanLepage** [comment]
This module is now ready for review/test !

**Comment by GaetanLepage** [comment]
Once https://github.com/NixOS/nixpkgs/pull/296402 will be merged, I will be able to add the remaining adapters.

**Comment by purepani** [comment]
Wow! Appreciate the incredibly quick work on this!

**Review by traxys — APPROVED** [review]

**Pull request merged**
