### PR TITLE
plugins.preview: init

### LINKED ISSUE #1577: [PLUGIN REQUEST] `Preview.nvim` (+ md-tui)
| Field    | Description |
|----------|-------------|
| Plugin   | `Preview.nvim`  | 
| Homepage | `https://github.com/henriklovhaug/Preview.nvim`     | 
| Nixpkgs  | `false` | 

## Extra Information

Demo of markdown preview in terminal, which is pretty cool:

https://x.com/orhundev/status/1795080714192347445

Package used,
https://github.com/henriklovhaug/md-tui

### PR DESCRIPTION
**Pull request by GaetanLepage**
Add support for [Preview.nvim](https://github.com/henriklovhaug/Preview.nvim).

Fixes #1577

### CODE REVIEW

**Review by MattSturgeon — APPROVED** [review]
LGTM

**Comment by GaetanLepage** [comment]
@Mergifyio queue

**Comment by ForsakenHarmony** [comment]
Seems like it's not in `nixpkgs-unstable` yet?

My build on darwin is broken now

**Comment by MattSturgeon** [comment]
@ForsakenHarmony you probably have nixvim following your nixpkgs input, which is likely behind.

Running `nix flake update` should resolve the issue. Worst case remove the follows line and re-run `nix flake lock`.

**Comment by ForsakenHarmony** [comment]
@MattSturgeon running `nix flake update` is what caused the issue﻿﻿

with the nixpkgs input being set to
```
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
```

but it seems to work now, so idk

**Comment by MattSturgeon** [comment]
@ForsakenHarmony not sure if you're aware, but nixpkgs-unstable is different to nixos-unstable.

Your nixpkgs input _should_ only affect nixvim if you have a "follows" line.

**Comment by ForsakenHarmony** [comment]
@MattSturgeon ah right, seems we kinda talked past each other with `nixpkgs` vs `nixos` 🙈

**Pull request merged**
