### PR TITLE
Add jupytext python3Dependency to jupytext plugin

### PR DESCRIPTION
**Pull request by bkp5190**
# Description
Add jupytext python3 Dependency for the juptext plugin

#2367

### CODE REVIEW

**Review by traxys — COMMENTED** [review]
I think that by itself this does nothing, you need to add the value to the `extraPython3Packages` global option. I think molten.nvim does that

**Comment by bkp5190** [comment]
Ah I see, thank you! Looks like I was missing a portion of the change. Does that override seem correct? - Similar to molten.nvim

**Review by GaetanLepage — APPROVED** [review]
LGTM, thanks !

**Review by traxys — APPROVED** [review]

**Comment by traxys** [comment]
@mergifyio queue

**Pull request merged**
