### PR TITLE
plugins/catppuccin: add `disableUnderline` option

### PR DESCRIPTION
**Pull request by mrtnvgr**
This PR adds support for `no_underline` option of catppuccin colorscheme.

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Could you please modify the test file accordingly ?
By the way, there is typo (`poimandres` -> `catppuccin`) at [this line](https://github.com/nix-community/nixvim/blob/main/tests/test-sources/plugins/colorschemes/catppuccin.nix#L7). Could you correct it at the same time ?

**Comment by mrtnvgr** [comment]
@GaetanLepage I don't understand why CI fails...

**Comment by traxys** [comment]
I think it is due to formatting

**Review by GaetanLepage — APPROVED** [review]
LGTM
Thank you for your contribution :)

**Pull request merged**
