### PR TITLE
colorschemes/dracula-nvim: fixes

### PR DESCRIPTION
**Pull request by khaneliman**
Follow up to https://github.com/nix-community/nixvim/pull/2153

Closes https://github.com/nix-community/nixvim/pull/2155

### CODE REVIEW

**Review by MattSturgeon — APPROVED** [review]
Thanks for cleaning up after me!

**Comment by MattSturgeon** [comment]
Ah, also need to update the test:

```
              error: The option `plugins.dracula' does not exist. Definition values:
              - In `<unknown-file>':
                  {
                    enable = true;
                  }
```

**Comment by khaneliman** [comment]
Forgot about the tests, just pushed those fixes.

**Comment by khaneliman** [comment]
Hmm. Changed luaName to account for the setup call, but still see:

```bash
 > ERROR: Error detected while processing /nix/store/ksmvjpg77ilcxp14d7qlm0afyvcf7m8d-init.lua:
       > E5113: Error while calling lua chunk: vim/_editor.lua:0: /nix/store/ksmvjpg77ilcxp14d7qlm0afyvcf7m8d-init.lua..nvim_exec2() called at /nix/store/ksmvjpg77ilcxp14d7qlm0afyvcf7m8d-init.lua:0: Vim(colorscheme):E185: Cannot find color scheme 'dracula-nvim'
```

**Comment by khaneliman** [comment]
Didn't realize we had a top level `colorscheme` property for that.... lol

**Comment by khaneliman** [comment]
@mergifyio queue

**Comment by GaetanLepage** [comment]
Thank you guys !

**Pull request merged**
