### PR TITLE
[main] Update flake.lock & generated files

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Flake lockfile
```
Flake lock file updates:

• Updated input 'flake-parts':
    'github:hercules-ci/flake-parts/9227223f6d922fee3c7b190b2cc238a99527bbb7' (2024-07-03)
  → 'github:hercules-ci/flake-parts/8471fe90ad337a8074e957b69ca4d0089218391d' (2024-08-01)
• Updated input 'home-manager':
    'github:nix-community/home-manager/58cef3796271aaeabaed98884d4abaab5d9d162d' (2024-07-31)
  → 'github:nix-community/home-manager/afc892db74d65042031a093adb6010c4c3378422' (2024-08-02)
• Updated input 'nix-darwin':
    'github:lnl7/nix-darwin/0413754b3cdb879ba14f6e96915e5fdf06c6aab6' (2024-07-27)
  → 'github:lnl7/nix-darwin/f7142b8024d6b70c66fd646e1d099d3aa5bfec49' (2024-08-02)
• Updated input 'nixpkgs':
    'github:NixOS/nixpkgs/52ec9ac3b12395ad677e8b62106f0b98c1f8569d' (2024-07-28)
  → 'github:NixOS/nixpkgs/9f918d616c5321ad374ae6cb5ea89c9e04bf3e58' (2024-07-31)
• Updated input 'nuschtosSearch':
    'github:NuschtOS/search/16565307c267ec219c2b5d3494ba66df08e7d403' (2024-07-28)
  → 'github:NuschtOS/search/3f5abffa5f28b4ac3c9212c81c5e8d2d22876071' (2024-08-01)

```

## Generate
No changes

### CODE REVIEW

**Comment by MattSturgeon** [comment]
CI is failing because it is attempting to build the generated rust-analyzer options package.

This is because all `checks` **and** `packages` are built during CI, and the rust-analyzer options is listed in the flake's `packages`.

Can't see any other issues, but do we want to merge something that will cause `nix flake check` to fail?

**Comment by MattSturgeon** [comment]
Sorry, didn't realize you had pushed to the main repo, so by running the CI again I've clobbered your PR.

**Comment by GaetanLepage** [comment]
> Sorry, didn't realize you had pushed to the main repo, so by running the CI again I've clobbered your PR.

I did trigger the action purposefully, no worry !

**Review by MattSturgeon — APPROVED** [review]
Assuming CI passes, I'm happy to bump the lock file without the generated files

**Comment by GaetanLepage** [comment]
@Mergifyio queue

**Pull request merged**
