### PR TITLE
plugins/none-ls: add typos

### PR DESCRIPTION
**Pull request by tarantoj**
Adds [`typos`](https://github.com/crate-ci/typos) to none-ls

### CODE REVIEW

**Review by GaetanLepage — APPROVED** [review]
LGTM thanks !

**Comment by tarantoj** [comment]
Just found out there is a real lsp, gonna have a crack at adding that too, but I suppose it doesn't hurt to have both?
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#typos_lsp

**Comment by GaetanLepage** [comment]
> Just found out there is a real lsp, gonna have a crack at adding that too, but I suppose it doesn't hurt to have both?

You will see, adding a language server is super easy. Look for recent PRs that have done it.

Sure we can have both.

**Comment by tarantoj** [comment]
Yeah, looks pretty straightforward! Will give it a go, but first I'll have to get typos-lsp upstreamed. Wish me luck!

**Comment by GaetanLepage** [comment]
> Yeah, looks pretty straightforward! Will give it a go, but first I'll have to get typos-lsp upstreamed. Wish me luck!

If you need some help for upstreaming the language server, tag me on your PR :)

**Pull request merged**
