### PR TITLE
misc: correct molten image provider options

### PR DESCRIPTION
**Pull request by ptonner**
fixes the option for `imageProvider` to match [configuration](https://github.com/benlubas/molten-nvim/tree/main#configuration) of molten (use "image.nvim" instead of "image_nvim")

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Thank you for this fix !
However, you have changed the formatting (no need to add `@args` at the beginning).
Please, make sure to run `nix fmt` before pushing :)

**Comment by ptonner** [comment]
ah crap, I forgot my bad

**Comment by ptonner** [comment]
(also, I think the `args` was there already. I can drop if needed)

**Comment by GaetanLepage** [comment]
> (also, I think the `args` was there already. I can drop if needed)

Indeed ! No, leave them, they are used.

**Review by GaetanLepage — APPROVED** [review]

**Pull request merged**
