### PR TITLE
plugins/blink-compat: init

### PR DESCRIPTION
**Pull request by HeitorAugustoLN**
Depends on NixOS/nixpkgs#365782

### CODE REVIEW

**Comment by HeitorAugustoLN** [comment]
Should be good to go now.

**Comment by traxys** [comment]
I think you need to rebase the branch on main to take into account the nixpkgs bump

**Comment by HeitorAugustoLN** [comment]
> I think you need to rebase the branch on main to take into account the nixpkgs bump

Oh yeah, you are right.

**Review by MattSturgeon — APPROVED** [review]
:rocket:

**Review by traxys — APPROVED** [review]

**Comment by traxys** [comment]
@mergify queue

**Comment by MattSturgeon** [comment]
@mergify requeue

**Comment by MattSturgeon** [comment]
@mergify queue

**Pull request merged**
