### PR TITLE
plugins/earthly: add plugin

### PR DESCRIPTION
**Pull request by DataHearth**
Added the <https://github.com/earthly/earthly.vim> plugin and its tests. No configuration is required.

### CODE REVIEW

**Comment by DataHearth** [comment]
Hey :wave:. It's my first PR in nixvim. Don't hesitate to tell me what I did wrong or just should add. Next PR will be better than this one ^^.

**Comment by DataHearth** [comment]
@MattSturgeon Thanks for the review ^^. It's fixed!

**Review by MattSturgeon — APPROVED** [review]
Great, thanks!

**Comment by MattSturgeon** [comment]
@mergifyio queue

**Pull request merged**
