### PR TITLE
plugins/lsp: Add some LSP servers

### PR DESCRIPTION
**Pull request by traxys**

### CODE REVIEW

**Review by khaneliman — APPROVED** [review]
Nice :) Wonder if we can communicate these in announcements somehow for people who might be interested

**Comment by traxys** [comment]
It may be a bit spammy :/

**Comment by traxys** [comment]
@mergify queue

**Comment by MattSturgeon** [comment]
> Nice :) Wonder if we can communicate these in announcements somehow for people who might be interested



> It may be a bit spammy :/

I think a single post with a brief summary is ok

**Pull request merged**
