### PR TITLE
Adding new example nixvim configuration

### PR DESCRIPTION
**Pull request by JMartJonesy**
Adding new configuration JMartJonesy/kickstart.nixvim

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Hi ! Thanks for this.
Could you please respect the alphabetical order please ?

**Comment by JMartJonesy** [comment]
Oops sure thing did not even notice the alphabetic ordering. I'll fix it

**Comment by JMartJonesy** [comment]
Ok it has been updated

**Review by MattSturgeon — COMMENTED** [review]
Thanks for adding your config.

My only concern is that the name will be confusing when [GaetanLepage/kickstart.nixvim](https://github.com/GaetanLepage/kickstart.nixvim) is also ready to be included.

On the other hand, I do value having multiple interpretations of kickstart.nvim in nix. There's also [kickstart-nix.nvim](https://github.com/nix-community/kickstart-nix.nvim), which doesn't use nixvim.

Adding "an" to the description helps a little, but I'm still unsure. I think @GaetanLepage should have the final say.

**Comment by GaetanLepage** [comment]
> As per my earlier comment [#1764 (review)](https://github.com/nix-community/nixvim/pull/1764#pullrequestreview-2144886099), I think @GaetanLepage should have the final say due to the name conflict.

Thanks for pointing this out.
I thought about it.
I will have a look at this project later and maybe use it in my kickstart.
I don't mind having this one listed here anyway.

**Pull request merged**
