### PR TITLE
plugins/cmp: add cmp-nixpkgs-maintainers source

### PR DESCRIPTION
**Pull request by GaetanLepage**
Add [cmp-nixpkgs-maintainers](https://github.com/GaetanLepage/cmp-nixpkgs-maintainers) source for `cmp`.
It auto-completes nixpkgs maintainers' GH handles when editing PR messages.

### CODE REVIEW

**Comment by khaneliman** [comment]
Seems like a darwin issue 
```bash
error: build of '/nix/store/nnkhza47jf3pfjgjv52nli08dyni6gj5-all-sources.drv' on 'ssh-ng://nix@darwin02.nix-community.org' failed: builder for '/nix/store/nnkhza47jf3pfjgjv52nli08dyni6gj5-all-sources.drv' failed with exit code 1;
       last 11 log lines:
       > ERROR: [cmp-nixpkgs-maintainers] Refreshing maintainers list.
       > Error detected while processing /nix/store/9i4gcj4ww7ghq11x4nrxx9crdn8prd5k-vimplugin-cmp-nixpkgs-maintainers-2024-10-12/after/plugin/cmp_nixpkgs_maintainers.lua:
       > E5113: Error while calling lua chunk: ...-unwrapped-0.10.2/share/nvim/runtime/lua/vim/_system.lua:244: ENOENT: no such file or directory
       > stack traceback:
       >         [C]: in function 'error'
       >       ...-unwrapped-0.10.2/share/nvim/runtime/lua/vim/_system.lua:244: in function 'spawn'
       >   ...-unwrapped-0.10.2/share/nvim/runtime/lua/vim/_system.lua:335: in function 'system'
       >  ...-maintainers/lua/cmp_nixpkgs_maintainers/maintainers.lua:38: in function 'refresh_cache'
       >    ...-maintainers/lua/cmp_nixpkgs_maintainers/maintainers.lua:69: in function 'refresh_cache_if_needed'
       >  ...nixpkgs-maintainers/lua/cmp_nixpkgs_maintainers/init.lua:32: in function 'new'
       >      ...ners-2024-10-12/after/plugin/cmp_nixpkgs_maintainers.lua:3: in main chunk
       For full logs, run 'nix log /nix/store/nnkhza47jf3pfjgjv52nli08dyni6gj5-all-sources.drv'.

**Comment by GaetanLepage** [comment]
> Seems like a darwin issue

No no, my plugin prints something by default. I pushed a change that allows to disable the printing.
Let's wait for it to land on `nixos-unstable`.

https://github.com/NixOS/nixpkgs/pull/348895

**Review by MattSturgeon — APPROVED** [review]
Awesome

**Comment by MattSturgeon** [comment]
```
all-sources> ERROR: [cmp-nixpkgs-maintainers] Refreshing maintainers list.

all-sources> Error detected while processing /nix/store/44s6w0s32xlr2jwb1irrlh5pia5q5qn1-vimplugin-cmp-nixpkgs-maintainers-2024-10-12/after/plugin/cmp_nixpkgs_maintainers.lua:

all-sources> E5113: Error while calling lua chunk: ...-unwrapped-0.10.2/share/nvim/runtime/lua/vim/_system.lua:244: ENOENT: no such file or directory

all-sources> stack traceback:

all-sources> [C]: in function 'error'

all-sources> ...-unwrapped-0.10.2/share/nvim/runtime/lua/vim/_system.lua:244: in function 'spawn'

all-sources> ...-unwrapped-0.10.2/share/nvim/runtime/lua/vim/_system.lua:335: in function 'system'

all-sources> ...-maintainers/lua/cmp_nixpkgs_maintainers/maintainers.lua:38: in function 'refresh_cache'

all-sources> ...-maintainers/lua/cmp_nixpkgs_maintainers/maintainers.lua:69: in function 'refresh_cache_if_needed'

all-sources> ...nixpkgs-maintainers/lua/cmp_nixpkgs_maintainers/init.lua:32: in function 'new'

all-sources> ...ners-2024-10-12/after/plugin/cmp_nixpkgs_maintainers.lua:3: in main chunk

error: build of '/nix/store/lindnpj0lbq447pkkj1hsnpczwagv6wq-all-sources.drv' on 'ssh-ng://nix@build04.nix-community.org' failed: builder for '/nix/store/lindnpj0lbq447pkkj1hsnpczwagv6wq-all-sources.drv' failed with exit code 1;

```

This definitely looks like a build failure rather than a test failure. Just printing output would a) fail on all systems and b) would show an error in CI about the unexpected output.

I think we could resolve the runtime output by having ways to "expect" specific output, but I think we'll still have the build failure above 🤔

**Comment by GaetanLepage** [comment]
I ended up fully disabling the test as this source invokes `nix` at startup which fails in the CI.

**Review by khaneliman — APPROVED** [review]

**Comment by GaetanLepage** [comment]
@mergify queue

**Comment by khaneliman** [comment]
https://github.com/khaneliman/khanelivim/commit/e24bcd66827a04903af25461ad4eee6605924e7a overlay to get latest version of package until it makes it into unstable.

**Pull request merged**
