### PR TITLE
Fix minor typo causing build failures.

### PR DESCRIPTION
**Pull request by bassforce86**
Relates to: #2693 

@khaneliman @MattSturgeon

### CODE REVIEW

**Review by GaetanLepage — APPROVED** [review]
I think that `devshells` is the correct name:
https://flake.parts/options/devshell

**Comment by bassforce86** [comment]
Yes, for flake-parts it is the correct name.

but it's then being referenced a an "actual" flake here: https://github.com/nix-community/nixvim/commit/bef9feb446a9203a1343a5026970396bcae60f6f#diff-53345b746dda1748bd7ce380e4c321cdaa5030738a87a73d320ac95e1a02981fR11

which is what's causing the break i think. I don't have enough background knowledge on why we want to reference the entire flake itself to comment on which area is best to change, but this seemed like to change with the smallest scope to mitigate the problem 🙂 

See flake output schema here: https://nixos.wiki/wiki/Flakes#Output_schema

**Review by GaetanLepage — CHANGES_REQUESTED** [review]
To be investigated further.

**Comment by HeitorAugustoLN** [comment]
I guess what is happening here, is that list-plugins/default.nix is depends on numtide/devshell, and is not disconsidered when input is removed

**Comment by MattSturgeon** [comment]
> I guess what is happening here, is that list-plugins/default.nix is depends on numtide/devshell, and is not disconsidered when input is removed

Correct, well deduced!

The issue is here:
https://github.com/nix-community/nixvim/blob/ba43815abf6b101c13fe1d8d93323ca2e1689315/flake-modules/dev/default.nix#L3-L9

The `./list-plugins` import should be conditional on the relevant inputs being present.

**Comment by HeitorAugustoLN** [comment]
#2699 should fix it

**Pull request closed without merging**
