### PR TITLE
plugins/neotest: add neotest-golang

### PR DESCRIPTION
**Pull request by hmajid2301**
Add [neotest-golang](https://github.com/fredrikaverpil/neotest-golang/). Which seems to resolve some issues with the current neotest-go adapter most people use. 

Fixes: #1995

### CODE REVIEW

**Comment by traxys** [comment]
Formatting issue:
```
       > diff --git a/tests/test-sources/plugins/neotest/default.nix b/tests/test-sources/plugins/neotest/default.nix
       > index efb1d5b..cc464ab 100644
       > --- a/tests/test-sources/plugins/neotest/default.nix
       > +++ b/tests/test-sources/plugins/neotest/default.nix
       > @@ -180,4 +180,3 @@
       >      };
       >    };
       >  }
       > -
```

**Comment by MattSturgeon** [comment]
Looks like there's still formatting issues, looks like it's just a trailing blank line.

```diff
diff --git a/tests/test-sources/plugins/neotest/default.nix b/tests/test-sources/plugins/neotest/default.nix
index efb1d5b..cc464ab 100644
--- a/tests/test-sources/plugins/neotest/default.nix
+++ b/tests/test-sources/plugins/neotest/default.nix
@@ -180,4 +180,3 @@
     };
   };
 }
-
```

The best way to deal with formatting is just to run `nix fmt`. You can also enable the pre-commit git hook by entering a devshell in the repo (`nix develop`), this hook enforces correct formatting when making a commit.

When this is fixed, could you squash your commits together so you just end up with one commit? If you're struggling I can help out.

I can't see any other issues, so I think this can be merged when these points are resolved. Thanks for your contribution!

**Comment by hmajid2301** [comment]
ahh of course how silly of me, that should be fixed hopefully!

**Review by GaetanLepage — APPROVED** [review]
LGTM !

**Review by MattSturgeon — APPROVED** [review]
Awesome, thanks! :tada:

**Comment by MattSturgeon** [comment]
@mergifyio queue

**Pull request merged**
