### PR TITLE
plugins/telescope: migrate helpers -> lib.nixvim

### PR DESCRIPTION
**Pull request by khaneliman**
Similar to https://github.com/nix-community/nixvim/pull/2052

### CODE REVIEW

**Comment by MattSturgeon** [comment]
CI failure looks like some option is broken?

**Comment by khaneliman** [comment]
@MattSturgeon looks like I missed one inherit, should be good now.

**Review by MattSturgeon — APPROVED** [review]
Awesome!

**Comment by khaneliman** [comment]
@mergifyio queue

**Comment by andrevmatos** [comment]
This broke `telescope/extensions/undo`:
```
       … while evaluating the option `content':

       … while evaluating definitions from `/nix/store/v4hljyypdk2sml3n10rgf4lvrxg3yapg-source/modules/output.nix':

       … while evaluating the option `extraConfigLua':

       … while evaluating definitions from `/nix/store/v4hljyypdk2sml3n10rgf4lvrxg3yapg-source/plugins/telescope':

       … while evaluating definitions from `/nix/store/v4hljyypdk2sml3n10rgf4lvrxg3yapg-source/plugins/telescope/extensions/undo.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: undefined variable 'mkRaw'
       at /nix/store/v4hljyypdk2sml3n10rgf4lvrxg3yapg-source/plugins/telescope/extensions/_helpers.nix:84:28:
           83|       '';
           84|       apply = mapAttrs (_: mkRaw);
             |                            ^
           85|     };
```

**Pull request merged**
