### PR TITLE
Update nixd options

### PR DESCRIPTION
**Pull request by nothendev**
- fixed formatting.command to be an array
- added options as in the docs
- updated link to options docs

This PR fixes some of the nixd options, which are outdated.

### CODE REVIEW

**Comment by nothendev** [comment]
oops

**Comment by MattSturgeon** [comment]
How does this relate to #1490 by @traxys ? I've not had chance to review either of these on a big enough display to fully appreciate the changes...

It seemed (at first glance) like the earlier PR was removing many of these options, perhaps to avoid documenting unstable options?

Is this PR something that #1490 could be rebased onto, or are the changes redundant/conflicting?

**Comment by nothendev** [comment]
@MattSturgeon
> How does this relate to https://github.com/nix-community/nixvim/pull/1490 by @traxys ?

Mine and theirs are equivalent and also mine is missing one option (`nixpkgs`).

I just didn't notice that and still PR'd.

**Comment by GaetanLepage** [comment]
I guess this can be closed now, right ?

**Comment by traxys** [comment]
Implemented in #1490

**Pull request closed without merging**
