### PR TITLE
Update flake.lock (main)

### LINKED ISSUE #1660: [BUG]  gdtoolkit is now (gdtoolkit_3|gdtoolkit_4)
| Field        | Description |
|--------------|-------------|
| Plugin       | `gdtoolkit`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

gdtoolkit is now gdtoolkit_3 and gdtoolkit_4

I am not actually using this lsp, but it's causing the flake to fail to build.
#1659 attempts to fix this but may need some changes.

### PR DESCRIPTION
**Pull request by GaetanLepage**
Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

```
Flake lock file updates:

• Updated input 'home-manager':
    'github:nix-community/home-manager/a7117efb3725e6197dd95424136f79147aa35e5b' (2024-06-04)
  → 'github:nix-community/home-manager/3d65009effd77cb0d6e7520b68b039836a7606cf' (2024-06-09)
• Updated input 'nix-darwin':
    'github:lnl7/nix-darwin/c0d5b8c54d6828516c97f6be9f2d00c63a363df4' (2024-05-29)
  → 'github:lnl7/nix-darwin/315aa649ba307704db0b16c92f097a08a65ec955' (2024-06-09)
• Updated input 'nixpkgs':
    'github:NixOS/nixpkgs/051f920625ab5aabe37c920346e3e69d7d34400e' (2024-06-07)
  → 'github:NixOS/nixpkgs/c7b821ba2e1e635ba5a76d299af62821cbcb09f3' (2024-06-09)
```

### Running GitHub Actions on this PR

GitHub Actions will not run workflows on pull requests which are opened by a GitHub Action.

To run GitHub Actions workflows on this PR, run:

```sh
git branch -D update_flake_lock_action
git fetch origin
git checkout update_flake_lock_action
git commit --amend --no-edit
git push origin update_flake_lock_action --force
```

Fixes #1660

### CODE REVIEW

**Comment by MattSturgeon** [comment]
I've cherry-picked https://github.com/nix-community/nixvim/pull/1659, which should resolve the build failure :crossed_fingers: (thanks @dezren39)

**Comment by MattSturgeon** [comment]
vimplugin-neotest-java test is still trying to run. Do we wait for a neotest fix upstream?

**Comment by MattSturgeon** [comment]
> neotest-playwright/pickers.lua:4: nvim-telescope/telescope.nvim is not installed

**Comment by GaetanLepage** [comment]
> neotest-playwright/pickers.lua:4: nvim-telescope/telescope.nvim is not installed

https://github.com/NixOS/nixpkgs/pull/319314

**Review by MattSturgeon — APPROVED** [review]

**Pull request merged**
