### PR TITLE
wrappers: add env-specific config as part of NixVim module

### PR DESCRIPTION
**Pull request by foo-dogsquared**
See #1074 for more details. I just went ahead to make this PR since discussion can also take place here anyways. ;p

### CODE REVIEW

**Comment by traxys** [comment]
I think this is a very good idea! We have a number of options that would benefit from this like choosing to install GCC or not for treesitter depending on standalone vs hmManager for example.

Though we need to add documentation for this feature, I'm not too sure where would be the best place

**Comment by foo-dogsquared** [comment]
> I think this is a very good idea! We have a number of options that would benefit from this like choosing to install GCC or not for treesitter depending on standalone vs hmManager for example.

Having install extra packages when deployed as standalone is also (very very) nice use case too!

> Though we need to add documentation for this feature, I'm not too sure where would be the best place

Documentation, what documentation? ;p

I suppose it would be best put in a user guide (if it has one like in #608).

**Comment by traxys** [comment]
For reference I added a documentation section in #1093, you can do something similar

**Comment by traxys** [comment]
An user guide was added in #1121!

**Comment by foo-dogsquared** [comment]
Added a section on the user guide.

**Review by traxys — APPROVED** [review]

**Pull request merged**
