### PR TITLE
dev/list-plugins: conditionally create devshell only if devshell input is present

### LINKED ISSUE #2693: [BUG] Build failures in darwin and nixos
| Field        | Description |
|--------------|-------------|
| Plugin       | `nixvim`  | home manager module issue
| Nixpkgs      | `unstable` | unstable
| Home Manager | `unstable` | unstable

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

I have encountered what I _think_ is a bug in the home manager module.

When running switch (from a flake, although I suspect the may also occur using channels) is a build failure when trying to create `devshells` which are imported from a flake, see error below/

```txt
 … while evaluating definitions from `/nix/store/18li13082730qixvnqc8wdvjlwckq532-source/wrappers/hm.nix':
       … while evaluating definitions from `/nix/store/s6agnzjr3kg5sayjy0b0ms52bkvifqrv-source/modules/transposition.nix':
       … while evaluating definitions from `/nix/store/s6agnzjr3kg5sayjy0b0ms52bkvifqrv-source/modules/perSystem.nix':
       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: The option `perSystem.aarch64-darwin.devshells' does not exist. Definition values:
       - In `/nix/store/18li13082730qixvnqc8wdvjlwckq532-source/flake-modules/dev/list-plugins, via option perSystem':
           {
             default = {
               commands = [
                 {
                   command = "/nix/store/m83ppxx1b0m7kn75mdqph66y2zixqw9l-list-plugins/bin/list-plugins \"$@\"";
           ...
```
this is on my Macbook using nix-darwin, however this also happens on my nixos system (x86_64-linux). I believe this is just a typo somewhere referencing `devshells` instead of `devShells`, but i'm not entirely sure where yet.

i'm able to mitigate this error by pinning nixvim to `ec24d496d52c2620b5ce3d237a2a1029a197b412`

error occurs when using nixvim at `30895485c3a31bb16ace513def4f3a36bfeb68c6`

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
}
```

### PR DESCRIPTION
**Pull request by HeitorAugustoLN**
Should fix #2693

### CODE REVIEW

**Review by GaetanLepage — APPROVED** [review]
Good thanks !

**Comment by GaetanLepage** [comment]
@HeitorAugustoLN thanks for all your contributions :)
Have you joined the matrix "Development" room ?

**Comment by GaetanLepage** [comment]
@mergify queue

**Comment by HeitorAugustoLN** [comment]
> @HeitorAugustoLN thanks for all your contributions :) Have you joined the matrix "Development" room ?

Yeah, I am there.

**Pull request merged**
