### PR TITLE
plugins/vim-be-good: init

### PR DESCRIPTION
**Pull request by 347Online**
Integrate the [vim-be-good](https://github.com/ThePrimeagen/vim-be-good) plugin

### CODE REVIEW

**Comment by traxys** [comment]
Could you split the PR in two commits, one for adding yourself to the maintainers, and the other for the plugin + tests?

**Comment by 347Online** [comment]
@traxys No problem

**Comment by traxys** [comment]
If you have both `hasSettings = true` and `callSetup = false` you need to "apply" the settings in some manner, I'm not sure if this plugin has real "configuration" options

**Comment by 347Online** [comment]
@traxys Ahaha, oops, yeah that was definitely supposed to be hasSettings = false 😅 
That should be fixed now

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Review by MattSturgeon — APPROVED** [review]

**Review by traxys — APPROVED** [review]

**Comment by traxys** [comment]
@mergify queue

**Pull request merged**
