### PR TITLE
plugins/colorschemes/base16: switch to new package name

### LINKED ISSUE #1112: [BUG] No longer builds under home-manager.
| Field        | Description |
|--------------|-------------|
| Plugin       | `none`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

## Description

I have just pulled an update on my flake and it fails to build with the following error.

```
error:
       … while checking flake output 'nixosConfigurations'

         at «none»:0: (source not available)

       … while checking the NixOS configuration 'nixosConfigurations.loki'

         at /nix/store/94gag39fil45c81x34rragrb3radkhyh-source/lib/mkFlake.nix:132:7:

          131|     {
          132|       ${host.output}.${reverseDomainName} = host.builder ({
             |       ^
          133|         inherit (host) system;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Alias nvim-base16 is still in vim-plugins
```

I don't have any plugins enabled at all. 

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  enable = true;
}
```

### PR DESCRIPTION
**Pull request by chadcatlett**
Fixes #1112 with regards to the base16 package name being changed.

### CODE REVIEW

**Comment by chadcatlett** [comment]
Bah, looks like it also needs a flake update to update nixpkgs in the lock file.

**Comment by traxys** [comment]
Is this still required with https://github.com/NixOS/nixpkgs/pull/289539 ?

**Comment by devusb** [comment]
Even on unstable-small ([35c5863c29ce](https://github.com/NixOS/nixpkgs/commit/35c5863c29ce81199ded8a3384f4979b7793f5dc), so contains https://github.com/NixOS/nixpkgs/pull/289539) I do still need this to build with nixvim.

**Comment by GaetanLepage** [comment]
We will rename to `base16-nvim` when we will update our flake to the next `nixos-unstable` bump.
The latter will include https://github.com/NixOS/nixpkgs/pull/289539.
Progress tracked: https://nixpk.gs/pr-tracker.html?pr=289539

In the meantime, setting `nixpkgs.url = "github:nixos/nixpkgs/a4d4fe8c5002202493e87ec8dbc91335ff55552c";` should work.

**Comment by GaetanLepage** [comment]
Already done in https://github.com/nix-community/nixvim/commit/08f3289d34ef8b69cb2da768cb80777fe5a7f076 :)

**Pull request closed without merging**
