### PR TITLE
helpers/mkLuaFn: refactor description implementation

### PR DESCRIPTION
**Pull request by GaetanLepage**
This allows to pass an empty default.

### CODE REVIEW

**Comment by traxys** [comment]
Why would we want empty defaults instead of null?

**Comment by GaetanLepage** [comment]
> Why would we want empty defaults instead of a lua nil

I meant an empty default string to disable the `defaultDesc` block.
For instance, if the actual default value of the plugin needs a weird description.

**Comment by traxys** [comment]
I think #866 is the better approach

**Comment by GaetanLepage** [comment]
> I think #866 is the better approach

Indeed, closing.

**Pull request closed without merging**
