### PR TITLE
plugins/vim-dadbod: init, plugins/vim-dadbod-ui: init, plugins/vim-dadbod-completion: init

### PR DESCRIPTION
**Pull request by bkp5190**
# Description
Add vim-dadbod, vim-dadbod-ui, and vim-dadbod-completion

# Issue
#2389

### CODE REVIEW

**Review by GaetanLepage — COMMENTED** [review]
LGTM, please change the commits to have (in this order):
- `maintainers: add BoneyPatel`
- `plugins/xxxx: init`
- `plugins/yyyy: init`
- ...

**Comment by bkp5190** [comment]
> LGTM, please change the commits to have (in this order):
> 
> * `maintainers: add BoneyPatel`
> * `plugins/xxxx: init`
> * `plugins/yyyy: init`
> * ...

Updated!

**Comment by traxys** [comment]
I think that we should add the vim-dadbod-completion auto-enable behaviour for nvim-cmp

**Comment by bkp5190** [comment]
> I think that we should add the vim-dadbod-completion auto-enable behaviour for nvim-cmp 

Good call, would this entail adding vim-dadbod-completion as a completion source for nvim-comp?

**Comment by traxys** [comment]
Yeah, I don't remember exactly the way to do that, but it has something to do with `cmpSourcePlugins`, I see that `otter` & `codium-nvim` uses it.

**Comment by bkp5190** [comment]
> Yeah, I don't remember exactly the way to do that, but it has something to do with `cmpSourcePlugins`, I see that `otter` & `codium-nvim` uses it.

Added a change for this, however, not entirely sure this is correct.

**Comment by bkp5190** [comment]
Any additional thoughts on this @traxys ?

**Review by MattSturgeon — APPROVED** [review]
:rocket:

**Comment by bkp5190** [comment]
Thanks, may need some assistance with @mergify queue

**Comment by MattSturgeon** [comment]
> Thanks, may need some assistance with mergify queue

Of course.

I'll probably hold off and merge tomorrow, to give other maintainers a chance to look.

Also, it's 1am here so I'd rather avoid merging anything with tired eyes :sleeping:

**Review by GaetanLepage — APPROVED** [review]

**Comment by MattSturgeon** [comment]
@mergify queue

**Pull request merged**
