### PR TITLE
fix(helpers): use "__unkeyed" prefix instead of "@" in `toLuaObject`

### LINKED ISSUE #627: can't define treesitter capture highlight groups starting with `@`
**Plugin affected**: n/a
**Nixpkgs channel**: unstable
**Home-manager version**: 23.11-pre

## Description

due to the definition of `helpers.toLuaObject`, key names in `nixvim.highlight` cannot begin with `@`. but treesitter highlight groups start with `@`: <https://github.com/nvim-treesitter/nvim-treesitter#highlight>

is there a workaround for this? or do we want to discuss an alternative to `@` in `toLuaObject`?

## Config

<https://codeberg.org/municorn/dotfiles/src/branch/nixvim/homes/muni/nvim/highlight.nix>

### PR DESCRIPTION
**Pull request by muni-corn**
so that neovim (treesitter) highlight groups can start with "@".

this may break existing configs which use "@" for key-less table entries.

i'm open to other solutions or a different prefix name :)

closes #627

### CODE REVIEW

**Review by traxys — CHANGES_REQUESTED** [review]
There are some places where the syntax was used in nixvim, like in `tests/lib-tests.nix`, `plugins/statusline/lualine.nix`, `plugins/filetrees/neo-tree.nix`, `plugins/utils/oil.nix`

**Comment by GaetanLepage** [comment]
Thank you for your proposition !
I think that this change is possible.
Could you look at the occurences of `@`-prefixed keys in the nixvim repo please ?
They would need to be fixed in the same PR.

**Comment by muni-corn** [comment]
on it! o7

**Comment by muni-corn** [comment]
done 😎

**Review by pta2002 — APPROVED** [review]

**Review by GaetanLepage — APPROVED** [review]

**Review by traxys — APPROVED** [review]

**Pull request merged**
