### PR TITLE
config-examples: Added fred-drake/neovim configuration

### PR DESCRIPTION
**Pull request by fred-drake**
Added configuration which attempts to take the most useful aspects from other configurations, primarily in the area of development with popular languages.

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Thank you for sharing your config !
Can you please limit your PR to the addition of your config please ?

**Comment by fred-drake** [comment]
> Thank you for sharing your config ! Can you please limit your PR to the addition of your config please ?

@GaetanLepage Done!  Sorry, my markdown formatter caught it.

**Comment by GaetanLepage** [comment]
> @GaetanLepage Done! Sorry, my markdown formatter caught it.

Thanks ! Can I also ask you to squash your commits into a single one please ?

**Comment by fred-drake** [comment]
I'm having issues squashing what is already pushed to upstream, so I am going to kill this and resubmit.

**Comment by MattSturgeon** [comment]
> I'm having issues squashing what is already pushed to upstream, so I am going to kill this and resubmit.

Thanks for sorting everything! As an FYI for future work, and to try and explain why you had issues:

When you squash or rebase, you're re-writing your git history. You can imagine a re-write as _essentially_ taking a fresh branch, then copying the same changes as before, but as brand new commits.

`git push` will therefore complain that you have a different history locally to what is on the remote.

This is a good thing to complain about, because you usually wouldn't want to re-write "public" branch history (which others may have cloned).

In the case of a PR feature-branch, though, you can safely use `git push -f` (`--force`). This instructs git to push anyway, overwriting the remote branch.

**Pull request closed without merging**
