### PR TITLE
plugins/debugprint-nvim: init

### PR DESCRIPTION
**Pull request by trueNAHO**
Add support for the https://github.com/andrewferrier/debugprint.nvim plugin.

Notes:

- Although, this plugin works in my Nixvim configuration, I am currently unable to run the added tests due to my system setup. Could someone try them for me?
- Once https://github.com/NixOS/nixpkgs/pull/270968 lands, the hard-coded `pkgs.vimUtils.buildVimPlugin` statement can be replaced by the Nixpkgs package.

Closes: https://github.com/nix-community/nixvim/issues/763

Requires:

- https://github.com/NixOS/nixpkgs/pull/270968
- https://github.com/NixOS/nixpkgs/pull/271007

### CODE REVIEW

**Comment by GaetanLepage** [comment]
I opened a PR to add debugprint to nixpkgs but forgot to mention it here sorry !

**Comment by trueNAHO** [comment]
> I opened a PR to add debugprint to nixpkgs but forgot to mention it here sorry !

No worries. Thanks for all the hard work.

**Comment by trueNAHO** [comment]
For reference, here is my current Nixvim connfiguration for this PR: https://github.com/trueNAHO/dotfiles/commit/378b53db1d06bb5f6c30ac0c8b146f68dfb4417a.

**Comment by trueNAHO** [comment]
Superseded by: https://github.com/nix-community/nixvim/pull/821

**Pull request closed without merging**
