### PR TITLE
plugins/none-ls: add google-java-format

### PR DESCRIPTION
**Pull request by redyf**
Add an option to enable google-java-format none-ls source.

### CODE REVIEW

**Comment by traxys** [comment]
I think you encountered a bug in the way we make the none ls config, seeing the arithmetic error :/

**Comment by redyf** [comment]
> I think you encountered a bug in the way we make the none ls config, seeing the arithmetic error :/

What should I do? That's pretty much the only thing holding me back from switching to none-ls. ;-;

**Comment by traxys** [comment]
I think you need `_` instead of `-`. See https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md#google_java_format

**Comment by redyf** [comment]
That makes sense, I'll try again in a bit

**Pull request closed without merging**
