### PR TITLE
plugins/fidget: adapt to latest rewrite of the plugin

### PR DESCRIPTION
**Pull request by GaetanLepage**
fidget.nvim [has been rewritten](https://github.com/j-hui/fidget.nvim/pull/143).
Hence, the options have changed significantly.

This PR updates our module to fit the upstream options.

### CODE REVIEW

**Comment by siph** [comment]
This closes #818

**Review by traxys — CHANGES_REQUESTED** [review]
I'd say some options lack documentations, as it is not explained what `false` does for progress.pollRate.

There are more details in https://github.com/j-hui/fidget.nvim/blob/main/doc/fidget-option.txt, maybe we should include a bit more documentation (maybe not everything though, I don't know?)

**Comment by GaetanLepage** [comment]
I added the complete description of all options.
I also fixed some mistakes that were present initially (missing options and wrong types).

**Comment by traxys** [comment]
Missing skipHistory options:
- https://github.com/j-hui/fidget.nvim/blob/a4a7edfea37e557dbff5509ee374ffb57051bba9/doc/fidget-option.txt#L312-L320
- https://github.com/j-hui/fidget.nvim/blob/a4a7edfea37e557dbff5509ee374ffb57051bba9/doc/fidget-option.txt#L409 in notificationOptions

**Comment by GaetanLepage** [comment]
> Missing skipHistory options:

Good catch.

**Review by traxys — APPROVED** [review]

**Pull request merged**
