### PR TITLE
Update config-examples.md with my Nixvim Config

### PR DESCRIPTION
**Pull request by dc-tec**
Added my nixvim config to the list of examples

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Thanks for your contribution !
Could you please respect the alphabetical order ?

**Comment by dc-tec** [comment]
Yes, ofcourse, ill fix it

**Review by GaetanLepage — APPROVED** [review]
Thanks !

**Review by MattSturgeon — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
