### PR TITLE
plugins/treesitter: fix folding

### PR DESCRIPTION
**Pull request by khaneliman**
opts getting wiped out by setting entire set as default instead of each attribute

### CODE REVIEW

**Review by MattSturgeon — APPROVED** [review]
I'm surprised moving the mkDefault to the specific attrs makes a difference, but if it works then today I've learnt something!

**Comment by khaneliman** [comment]
> I'm surprised moving the mkDefault to the specific attrs makes a difference, but if it works then today I've learnt something!

My assumption was that it basically treated the entire attribute set as the default definition for opts and then providing another opts attribute overrode it? 

I have library functions in my repo for doing this on nested attributes I think for this reason.
```nix
default-attrs = mapAttrs (_key: mkDefault);

nested-default-attrs = mapAttrs (_key: default-attrs);
```

**Comment by MattSturgeon** [comment]
@mergifyio queue

**Comment by MattSturgeon** [comment]
Thanks again! 👍

**Pull request merged**
