### PR TITLE
plugins/yazi: remove unnecessary extraPlugin; plugins/markview: remove unnecessary extraPlugin

### PR DESCRIPTION
**Pull request by khaneliman**

### CODE REVIEW

**Review by GaetanLepage — APPROVED** [review]

**Comment by MattSturgeon** [comment]
```
error: hash mismatch in fixed-output derivation '/nix/store/jl63hzr355zarhjlr50v887giyq8062n-dkjson-2.8.tar.gz.drv':
         specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
            got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
```

Looks like a nixpkgs issue? Is this also affecting the base update PR?

**Comment by khaneliman** [comment]
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/jl63hzr355zarhjlr50v887giyq8062n-dkjson-2.8.tar.gz.drv':
>          specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
>             got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
> ```
>
> Looks like a nixpkgs issue? Is this also affecting the base update PR?

Yeah, I can replicate it on nixos-unstable branch.

**Comment by GaetanLepage** [comment]
> Looks like a nixpkgs issue? Is this also affecting the base update PR?

Yes, but this one should not be present on *our* revision of nixpkgs, right ?
(hopefully it has been fixed upstream)

**Comment by MattSturgeon** [comment]
> > Looks like a nixpkgs issue? Is this also affecting the base update PR?
> 
> Yes, but this one should not be present on _our_ revision of nixpkgs, right ? (hopefully it has been fixed upstream)

This PR was based on (and targeting) the update PR branch. You're right this doesn't affect the nixpkgs lock we have on the `main` branch.

**Comment by GaetanLepage** [comment]
Oh, I hadn't noticed, thanks.

**Pull request merged**
