### PR TITLE
plugins/nvim-bacon: init

### PR DESCRIPTION
**Pull request by alisonjenkins**
Will resolve: https://github.com/nix-community/nixvim/issues/1025

There is not yet a package on Nixpkgs though so need to open a PR for it.

### CODE REVIEW

**Comment by GaetanLepage** [comment]
I have opened a PR on nixpkgs to add `nvim-bacon`: https://github.com/NixOS/nixpkgs/pull/288660

However, this plugin will surely benefit from our new `mkNeovimPlugin` helper.
We should then wait for #1030 to be merged (soon I hope).

**Comment by GaetanLepage** [comment]
> Thanks for doing that, I was trying to figure out how to do it myself last night but was having problems with the nixpkgs vim plugin tool getting rate limited. I see from the PR though that I was running the wrong command and there is one for just adding the individual plugin rather than doing a full run.

Yes, you actually don't have to run the tool without arguments (which updates everything). You can simply use the `--add` flag that will add it in the `vim-plugin-names` file.
However, you will need to manually add the correct snippet to `.../vim/pluging/generated.nix`. This is what I have done here.

**Comment by GaetanLepage** [comment]
> I have opened a PR on nixpkgs to add `nvim-bacon`: [NixOS/nixpkgs#288660](https://github.com/NixOS/nixpkgs/pull/288660)

Merged: https://nixpk.gs/pr-tracker.html?pr=288660

**Comment by GaetanLepage** [comment]
The PR has landed to the unstable channels. You can rebase on `main` and resume your implementation :)

**Comment by traxys** [comment]
Same as baleia, could you please put everything in a `plugins/utils/bacon.nix` file?

**Review by traxys — APPROVED** [review]

**Pull request merged**
