### PR TITLE
plugins/lsp: add htmx lsp

### LINKED ISSUE #933: LSP: `htmx-lsp`
It is available in the [`neovim/nvim-lspconfig` `server_configurations.md`](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#htmx) and also in nixpkgs as `htmx-lsp`.

### PR DESCRIPTION
**Pull request by GaetanLepage**
Add support for [htmx-lsp](https://github.com/ThePrimeagen/htmx-lsp).

Fixes #933

### CODE REVIEW

**Review by traxys — APPROVED** [review]

**Comment by hbjydev** [comment]
Should be noted that this means that `nixvim` now depends on using nixpkgs unstable. `htmx-lsp` doesn't exist in `release-23.11`

**Comment by GaetanLepage** [comment]
> Should be noted that this means that `nixvim` now depends on using nixpkgs unstable. `htmx-lsp` doesn't exist in `release-23.11`

Not really, it means that users of the `nixos-23.11` branch will not have the option to enable the `htmx-lsp`  language server.
We do not backport new plugins/options to stable releases.

**Comment by hbjydev** [comment]
> > Should be noted that this means that `nixvim` now depends on using nixpkgs unstable. `htmx-lsp` doesn't exist in `release-23.11`
> 
> Not really, it means that users of the `nixos-23.11` branch will not have the option to enable the `htmx-lsp` language server. We do not backport new plugins/options to stable releases.

When I tried to build using `release-23.11` it wouldn't even build the derivation because `pkgs.htmx-lsp` didn't exist

**Comment by GaetanLepage** [comment]
> When I tried to build using `release-23.11` it wouldn't even build the derivation because `pkgs.htmx-lsp` didn't exist

Are you sure to have both `nixpkgs` and `nixvim` following their respective `nixos-23.11` branch ?
This problem sounds like you are following the `main` branch of `nixvim` while following the `nixos-23.11` `nixpkgs` channel.

**Comment by hbjydev** [comment]
> > When I tried to build using `release-23.11` it wouldn't even build the derivation because `pkgs.htmx-lsp` didn't exist
> 
> Are you sure to have both `nixpkgs` and `nixvim` following their respective `nixos-23.11` branch ? This problem sounds like you are following the `main` branch of `nixvim` while following the `nixos-23.11` `nixpkgs` channel.

Ah, that's probably it! Sorry about that :D

**Comment by GaetanLepage** [comment]
> > > When I tried to build using `release-23.11` it wouldn't even build the derivation because `pkgs.htmx-lsp` didn't exist
> > 
> > 
> > Are you sure to have both `nixpkgs` and `nixvim` following their respective `nixos-23.11` branch ? This problem sounds like you are following the `main` branch of `nixvim` while following the `nixos-23.11` `nixpkgs` channel.
> 
> Ah, that's probably it! Sorry about that :D

No problem !

**Pull request merged**
