### PR TITLE
plugins/luasnip: backport SnipMate loader

### PR DESCRIPTION
**Pull request by cezdro**
I created this commit some time ago (under @nawordar account), but I drive NixOS stable and the `main` branch of NixVim is not compatible anymore (missing cmp-ai package).

### CODE REVIEW

**Comment by MattSturgeon** [comment]
Is this purely additions with no changes to existing options? We don't normally backport, but I'm fine with merging the occasional backport if is additive only and has no breaking changes.

I'm not sure what's going on with the CI failure, it may be unrelated.

I'd like to point out though, it is possible to use the `main` nixvim branch by doing a standalone build and then including the package in your system packages. But this is a slightly different workflow to using the nixos/hm/darwin modules.

In the future (#1784), it should be possible to tell nixvim to use a different `pkgs` to your system modules. That would also allow you to have a mixed build where you use 24.05 on the host and unstable in nixvim.

**Comment by cezdro** [comment]
I'm using NixVim as a home-manager module and home-manager as a NixOS module. I tried adding `inputs.nixvim.inputs.nixpkgs.follows = "nixpkgs-unstable"`, but it didn't change anything. Do I understand correctly that home-manager still passes the 24.05 branch of nixpkgs?

Yes, this commit only adds an option and does some clean up as discussed in #1643.

**Comment by MattSturgeon** [comment]
> I'm using NixVim as a home-manager module and home-manager as a NixOS module.

Yes, currently the only way to use a nixvim from unstable on a system running a stable channel is to use nixvim's standalone build method, linked above.

> I tried adding `inputs.nixvim.inputs.nixpkgs.follows = "nixpkgs-unstable"`, but it didn't change anything. Do I understand correctly that home-manager still passes the 24.05 branch of nixpkgs?

Correct, that's what #1784 is about; adding a way to configure `programs.nixvim.nixpkgs.pkgs`.

> Yes, this commit only adds an option and does some clean up as discussed in #1643.

Thanks for clarifying!

> Unfortunately, I don't have a Mac, so I can't test what is going on with the test

Yes, Darwin can be a bit of a pain; some tests just don't run well on it.

**Review by MattSturgeon — APPROVED** [review]

**Comment by MattSturgeon** [comment]
@mergifyio queue

**Pull request merged**
