### PR TITLE
plugins/ltex-extra: init

### PR DESCRIPTION
**Pull request by loicreynier**
Add an option to `plugins.lsp.servers.ltex` to enable the [LTeX_extra](https://github.com/barreiroleo/ltex_extra.nvim) plugins which enable LTeX LSP code action, external file handling and more features. 

I let this PR as a draft as I have not properly tested it yet and I am not sure if adding this plugin as an option to `plugins.lsp.servers.ltex` is the preferred way.

### CODE REVIEW

**Review by traxys — COMMENTED** [review]
We have some other plugins that do stuff like this, like clangd_extensions & rustacean.nvim, you could check how they do things.

**Comment by traxys** [comment]
Sorry I have forgotten to mention that new plugins should try to use the `mkNeovimPlugin` helper (see for occurences). This will require a bit of a refactor :/

**Comment by loicreynier** [comment]
> It looks like the upstream options are in `snake_case`: [barreiroleo/ltex_extra.nvim#configuration](https://github.com/barreiroleo/ltex_extra.nvim?tab=readme-ov-file#configuration)
> 
> We need the names to match for the module to work.

Thanks for the heads up. I just realized it testing it. I'll fix it right away.

**Comment by loicreynier** [comment]
Tested locally, seems to work fine.

**Review by traxys — APPROVED** [review]

**Pull request merged**
