### PR TITLE
 modules/diagnostics: rename source file + add test

### PR DESCRIPTION
**Pull request by GaetanLepage**

### CODE REVIEW

**Review by MattSturgeon — APPROVED** [review]
LGTM. I'd have happily done this as review feedback in the original PR, but thanks for taking care of it!

**Comment by GaetanLepage** [comment]
> LGTM. I'd have happily done this as review feedback in the original PR, but thanks for taking care of it!

Indeed, but it's on me: I have missed it during my review :/

**Comment by MattSturgeon** [comment]
git-octo failing again :sob:

**Comment by GaetanLepage** [comment]
> git-octo failing again 😭

https://github.com/nix-community/nixvim/pull/1740

**Pull request merged**
