### PR TITLE
plugins/cmp-git: move to by-name

### PR DESCRIPTION
**Pull request by GaetanLepage**

### CODE REVIEW

**Comment by khaneliman** [comment]
m

**Comment by GaetanLepage** [comment]
Oops, went too fast on the CLI!

**Comment by MattSturgeon** [comment]
> ``error: path '/nix/store/XXX-source/plugins/by-name/cmp-git/settings-options' does not exist``

Also: conflict

**Review by MattSturgeon — APPROVED** [review]

**Comment by GaetanLepage** [comment]
@mergify queue

**Pull request merged**
